In [1]:
import pandas as pd
import numpy as np
employees = pd.DataFrame({
    "EmployeeID": [101,102,103,104,105,106,107,108,109,110],
    "Name": [
        "Aman Kumar", "Riya Sharma", "Rahul Kumar", "Priya Singh",
        "Karan Mehta", "Neha Gupta", "Arjun Verma", "Sneha Das",
        "Rohit Kumar", "Anjali Sharma"
    ],
    "Department": [
        "Sales", "IT", "Sales", "HR", "IT",
        "Sales", "HR", "IT", "Sales", "HR"
    ],
    "Age": [24, 28, 31, 26, 35, np.nan, 29, 24, 32, 27],
    "Salary": [
        35000, 55000, 48000, 42000, 65000,
        39000, 45000, 58000, 52000, 41000
    ],
    "Experience": [1, 4, 7, 3, 10, 2, 5, 3, 8, 2],
    "Performance": [78, 92, 85, 74, 95, 68, 88, 91, 82, 76]
})

In [ ]:
# ============================================================
#              PANDAS PRACTICE ASSIGNMENT
#                    QUESTIONS 1–26
# ============================================================

# Q1 — Select Columns
# Select the Name, Department, and Salary columns.

# Q2 — Conditional Filtering
# Find employees with Salary > 50000 and Performance > 85.
# Display Name, Salary, and Performance.

# Q3 — Using .isin()
# Find employees belonging to IT or Sales.
# Display Name, Department, and Salary.

# Q4 — Using .between()
# Find employees whose Age is between 25 and 32 (inclusive).
# Display Name, Age, and Department.

# Q5 — Multiple Conditions
# Find employees who:
# - Belong to IT or Sales
# - Have Salary between 40000 and 60000
# - Have Performance > 80
# Display Name, Department, Salary, and Performance.

# Q6 — Create a New Column
# Create Annual_Salary = Salary * 12.

# Q7 — Performance Level
# Create Performance_Level using np.where():
# - Performance >= 90 → Excellent
# - Performance >= 80 → Good
# - Performance >= 70 → Average
# - Otherwise → Needs Improvement

# Q8 — Extract First Name
# Create First_Name by extracting the first name from Name.
# Example: "Aman Kumar" → "Aman"

# Q9 — Extract and Filter Last Name
# Extract the last name from Name.
# Find employees whose last name is Kumar.
# Display Name, Department, and Salary.

# Q10 — String Transformation
# Create Name_Upper containing names in uppercase.

# Q11 — GroupBy
# Calculate the average Salary for each Department.

# Q12 — Multiple Aggregations
# For each Department, calculate:
# - Employee count
# - Average Salary
# - Maximum Salary
# - Minimum Salary
# - Average Performance

# Q13 — Filter + GroupBy
# Consider employees with Performance > 80.
# Calculate the average Salary for each Department.

# Q14 — GroupBy + Sorting
# Calculate average Salary for each Department.
# Sort from highest to lowest average Salary.

# Q15 — Maximum Annual Salary
# Find the maximum Annual_Salary for each Department.

# Q16 — Filter + Multiple Aggregations
# Consider employees with:
# - Experience >= 3
# - Performance >= 80
# For each Department, calculate:
# - Employee count
# - Average Salary
# - Average Performance
# - Maximum Salary
# Sort by Average Salary descending.

# Q17 — Department Performance Report
# For each Department, calculate:
# - Employee count
# - Average Salary
# - Average Performance
# - Maximum Performance
# - Minimum Performance
# Sort by Average Performance descending.

# Q18 — High Performers
# Find employees who:
# - Performance >= 85
# - Salary > 40000
# - Experience >= 3
# Display Name, Department, Salary, Experience, Performance.
# Sort by Performance descending.

# Q19 — Missing Values
# Find the number of missing values in every column.

# Q20 — Handle Missing Age
# Fill missing Age values using the median Age.
# Verify that no missing values remain in Age.

# Q21 — Duplicate Check
# Check for duplicate rows.
# Display duplicate rows and count the total number of duplicates.

# Q22 — Merge / SQL INNER JOIN
# Merge employees and departments using Department.
# Use an INNER JOIN.
# Display Name, Department, Manager, and Office.

# Q23 — Extract Manager's Last Name
# Create Manager_Last_Name from Manager.
# Example: "Mr. Verma" → "Verma"

# Q24 — Filter After Merge
# From the merged DataFrame, find employees who:
# - Belong to IT or Sales
# - Have Performance > 85
# Display Name, Department, Manager, and Performance.

# Q25 — Complete Pandas Analysis
# 1. Create Annual_Salary.
# 2. Create Performance_Level.
# 3. Create First_Name.
# 4. Merge employees with departments.
# 5. Keep employees who:
#    - Belong to IT or Sales
#    - Have Performance >= 80
#    - Have Experience >= 3
# 6. Display:
#    - First_Name
#    - Department
#    - Manager
#    - Annual_Salary
#    - Experience
#    - Performance
#    - Performance_Level
# 7. Sort by Performance descending.

# Q26 — Final Department Analytics
# Create a department-level report containing:
# - Department
# - Employees
# - Avg_Salary
# - Avg_Experience
# - Avg_Performance
# - Max_Salary
# Sort by Avg_Performance descending.

# ============================================================
#                    END OF QUESTIONS
# ============================================================

In [2]:
employees[["Name", "Department", "Salary"]]

            Name Department  Salary
0     Aman Kumar      Sales   35000
1    Riya Sharma         IT   55000
2    Rahul Kumar      Sales   48000
3    Priya Singh         HR   42000
4    Karan Mehta         IT   65000
5     Neha Gupta      Sales   39000
6    Arjun Verma         HR   45000
7      Sneha Das         IT   58000
8    Rohit Kumar      Sales   52000
9  Anjali Sharma         HR   41000

In [3]:
# Q1 — Select Columns

# Select the Name, Department, and Salary columns from the employees DataFrame.
employees[
    (employees["Salary"] > 50000) &
    (employees["Performance"] > 85)
][["Name", "Salary", "Performance"]]

          Name  Salary  Performance
1  Riya Sharma   55000           92
4  Karan Mehta   65000           95
7    Sneha Das   58000           91

In [4]:
# Q2 — Conditional Filtering
# Find employees with Salary > 50000 and Performance > 85.
# Display Name, Salary, and Performance.

employees[
    employees["Department"].isin(["IT", "Sales"])
][["Name", "Department", "Salary"]]

          Name Department  Salary
0   Aman Kumar      Sales   35000
1  Riya Sharma         IT   55000
2  Rahul Kumar      Sales   48000
4  Karan Mehta         IT   65000
5   Neha Gupta      Sales   39000
7    Sneha Das         IT   58000
8  Rohit Kumar      Sales   52000

In [5]:
# Q4 — Using .between()
# Find employees whose Age is between 25 and 32 (inclusive).
# Display Name, Age, and Department.


employees[
    employees["Age"].between(25, 32)
][["Name", "Age", "Department"]]

            Name   Age Department
1    Riya Sharma  28.0         IT
2    Rahul Kumar  31.0      Sales
3    Priya Singh  26.0         HR
6    Arjun Verma  29.0         HR
8    Rohit Kumar  32.0      Sales
9  Anjali Sharma  27.0         HR

In [6]:
# Q5 — Multiple Conditions
# Find employees who:
# - Belong to IT or Sales
# - Have Salary between 40000 and 60000
# - Have Performance > 80
# Display Name, Department, Salary, and Performance.
employees[
    (employees["Department"].isin(["IT", "Sales"])) &
    (employees["Salary"].between(40000, 60000)) &
    (employees["Performance"] > 80)
][["Name", "Department", "Salary", "Performance"]]

          Name Department  Salary  Performance
1  Riya Sharma         IT   55000           92
2  Rahul Kumar      Sales   48000           85
7    Sneha Das         IT   58000           91
8  Rohit Kumar      Sales   52000           82

In [7]:
# Q6 — Create a New Column
# Create Annual_Salary = Salary * 12.

employees["Annual_Salary"] = employees["Salary"] * 12
employees["Annual_Salary"]

0    420000
1    660000
2    576000
3    504000
4    780000
5    468000
6    540000
7    696000
8    624000
9    492000
Name: Annual_Salary, dtype: int64

In [8]:
# Q7 — Performance Level
# Create Performance_Level using np.where():
# - Performance >= 90 → Excellent
# - Performance >= 80 → Good
# - Performance >= 70 → Average
# - Otherwise → Needs Improvement

employees["Performance_Level"] = np.where(
    employees["Performance"] >= 90,
    "Excellent",
    np.where(
        employees["Performance"] >= 80,
        "Good",
        np.where(
            employees["Performance"] >= 70,
            "Average",
            "Needs Improvement"
        )
    )
)

employees["Performance_Level"]

0              Average
1            Excellent
2                 Good
3              Average
4            Excellent
5    Needs Improvement
6                 Good
7            Excellent
8                 Good
9              Average
Name: Performance_Level, dtype: str

In [9]:
# Q8 — Extract First Name
# Create First_Name by extracting the first name from Name.
# Example: "Aman Kumar" → "Aman"

employees["First_Name"] = employees["Name"].str.split(" ").str[0]
employees["First_Name"]

0      Aman
1      Riya
2     Rahul
3     Priya
4     Karan
5      Neha
6     Arjun
7     Sneha
8     Rohit
9    Anjali
Name: First_Name, dtype: object

In [10]:
# Q9 — Extract and Filter Last Name
# Extract the last name from Name.
# Find employees whose last name is Kumar.
# Display Name, Department, and Salary.

employees["Last_name"] = employees["Name"].str.split(" ").str[1]

employees[
    employees["Last_name"] == "Kumar"
][["Name", "Department", "Salary"]]

          Name Department  Salary
0   Aman Kumar      Sales   35000
2  Rahul Kumar      Sales   48000
8  Rohit Kumar      Sales   52000

In [11]:
# Q10 — String Transformation
# Create Name_Upper containing names in uppercase.

employees["Name_Upper"] = employees["Name"].str.upper()
employees["Name_Upper"]

0       AMAN KUMAR
1      RIYA SHARMA
2      RAHUL KUMAR
3      PRIYA SINGH
4      KARAN MEHTA
5       NEHA GUPTA
6      ARJUN VERMA
7        SNEHA DAS
8      ROHIT KUMAR
9    ANJALI SHARMA
Name: Name_Upper, dtype: str

In [12]:
#Q11 groupyby():
#find the average salary for each department 
employees.groupby("Department")["Salary"].mean()

Department
HR       42666.666667
IT       59333.333333
Sales    43500.000000
Name: Salary, dtype: float64

In [15]:
#Q12: multiple aggregations
employees.groupby("Department").agg({
    "EmployeeID":"count",
    "Salary":"mean",
    "Salary":"max",
    "Salary":"min",
    "Performance":"mean"
})

            EmployeeID  Salary  Performance
Department
HR                   3   41000    79.333333
IT                   3   55000    92.666667
Sales                4   35000    78.250000

In [16]:
employees.groupby("Department").agg(
    Employee_Count=("EmployeeID", "count"),
    Avg_Salary=("Salary", "mean"),
    Max_Salary=("Salary", "max"),
    Min_Salary=("Salary", "min"),
    Avg_Performance=("Performance", "mean")
)

,Employee_Count,Avg_Salary,Max_Salary,Min_Salary,Avg_Performance
Department,,,,,
HR,3,42666.666667,45000,41000,79.333333
IT,3,59333.333333,65000,55000,92.666667
Sales,4,43500.000000,52000,35000,78.250000

In [18]:
#Q13: consideer only employees whose Performance > 80 , then calculate the average salary for 
#each department
employees[employees["Performance"]>80].groupby("Department")["Salary"].mean()

Department
HR       45000.000000
IT       59333.333333
Sales    50000.000000
Name: Salary, dtype: float64

In [20]:
#Q14: groupby + sorting 
#find the average salary for each department and then sort the departments
#from highest averagae salary to lowest average slary 
employees.groupby("Department")["Salary"].mean().sort_values(ascending = False)

Department
IT       59333.333333
Sales    43500.000000
HR       42666.666667
Name: Salary, dtype: float64

In [21]:
#Q15: groupby + created column 
#find the maximum annual salary for each department 
employees.groupby("Department")["Annual_Salary"].max()

Department
HR       540000
IT       780000
Sales    624000
Name: Annual_Salary, dtype: int64

In [28]:
#Q16: filter + groupby+multiple aggregations + sort
employees[
    (employees["Experience"]>=3)&
    (employees["Performance"]>=80)
    ].groupby("Department").agg(
    emp_count = ("EmployeeID","count"),
    ave_sal = ("Salary","mean"),
    ave_per = ("Performance","mean"),
    maxx_sal = ("Salary","max")
).sort_values(by = "ave_sal",ascending = False)

            emp_count       ave_sal    ave_per  maxx_sal
Department
IT                  3  59333.333333  92.666667     65000
Sales               2  50000.000000  83.500000     52000
HR                  1  45000.000000  88.000000     45000

In [29]:
# Q17 — Department Performance Report
# For each Department, calculate:
# - Employee count
# - Average Salary
# - Average Performance
# - Maximum Performance
# - Minimum Performance
# Sort by Average Performance descending.
employees.groupby("Department").agg(
    emp_count = ("EmployeeID","count"),
    ave_sal = ("Salary","mean"),
    ave_per = ("Performance","mean"),
    max_per = ("Performance","max"),
    min_per = ("Performance","min"),
).sort_values(by = "ave_per",ascending = False)

            emp_count       ave_sal    ave_per  max_per  min_per
Department
IT                  3  59333.333333  92.666667       95       91
HR                  3  42666.666667  79.333333       88       74
Sales               4  43500.000000  78.250000       85       68

In [31]:
#Q18: high performers 
#find employees qwho satisfy all three:
employees[
    (employees["Performance"] >= 85) & 
    (employees["Salary"] > 40000)&
    (employees["Experience"]>=3)
    ][["Name","Department","Salary","Experience","Performance"]].sort_values(by = "Performance",ascending = False)

          Name Department  Salary  Experience  Performance
4  Karan Mehta         IT   65000          10           95
1  Riya Sharma         IT   55000           4           92
7    Sneha Das         IT   58000           3           91
6  Arjun Verma         HR   45000           5           88
2  Rahul Kumar      Sales   48000           7           85

In [32]:
# Q19 — Missing Values
# Find the number of missing values in every column.
employees.isna().sum()

EmployeeID           0
Name                 0
Department           0
Age                  1
Salary               0
Experience           0
Performance          0
Annual_Salary        0
Performance_Level    0
First_Name           0
Last_name            0
Name_Upper           0
dtype: int64

In [36]:
# Q20 — Handle Missing Age
# Fill missing Age values using the median Age.
# Verify that no missing values remain in Age.
employees["Age"] = employees["Age"].fillna(employees["Age"].median())
employees["Age"].isna().sum()

np.int64(0)

In [40]:
# Q21 — Duplicate Check
# Check for duplicate rows.
# Display duplicate rows and count the total number of duplicates.
employees[employees.duplicated()]
employees.duplicated().sum()

np.int64(0)

In [43]:
#Dataset 2
departments = pd.DataFrame({
    "Department": ["Sales", "IT", "HR"],
    "Manager": ["Mr. Verma", "Ms. Sharma", "Mr. Singh"],
    "Office": [101, 202, 303]
})

In [45]:
# Q22 — Merge / SQL JOIN
# Merge employees and departments using Department.
# Use an INNER JOIN.
# Display Name, Department, Manager, and Office.
pd.merge(
    employees,
    departments,
    on ="Department",
    how = "inner"
)[["Name","Department","Manager","Office"]]

            Name Department     Manager  Office
0     Aman Kumar      Sales   Mr. Verma     101
1    Riya Sharma         IT  Ms. Sharma     202
2    Rahul Kumar      Sales   Mr. Verma     101
3    Priya Singh         HR   Mr. Singh     303
4    Karan Mehta         IT  Ms. Sharma     202
5     Neha Gupta      Sales   Mr. Verma     101
6    Arjun Verma         HR   Mr. Singh     303
7      Sneha Das         IT  Ms. Sharma     202
8    Rohit Kumar      Sales   Mr. Verma     101
9  Anjali Sharma         HR   Mr. Singh     303

In [51]:
#23: extract manger's last nam
# Q23 — Extract Manager's Last Name
# Create Manager_Last_Name from Manager.
# Example: "Mr. Verma" → "Verma"
departments["Mangers_last_name"]=departments["Manager"].str.split(" ").str[-1]

In [53]:
# Q24 — Filter After Merge
# From the merged DataFrame, find employees who:
# - Belong to IT or Sales
# - Have Performance > 85
# Display Name, Department, Manager, and Performance.
merged =pd.merge(
    employees,
    departments,
    on = "Department",
    how = "inner"
)
merged[
    merged["Department"].isin(["IT","Sales"]) &
    (merged["Performance"]>85)
    ][["Name","Department","Manager","Performance"]]

          Name Department     Manager  Performance
1  Riya Sharma         IT  Ms. Sharma           92
4  Karan Mehta         IT  Ms. Sharma           95
7    Sneha Das         IT  Ms. Sharma           91

In [65]:
# Q25 — Complete Pandas Analysis
# 1. Create Annual_Salary.
# 2. Create Performance_Level.
# 3. Create First_Name.
# 4. Merge employees with departments.
# 5. Keep employees who:
#    - Belong to IT or Sales
#    - Have Performance >= 80
#    - Have Experience >= 3
# 6. Display:
#    - First_Name
#    - Department
#    - Manager
#    - Annual_Salary
#    - Experience
#    - Performance
#    - Performance_Level
# 7. Sort by Performance descending.

#annual salary:
employees["Annual_Salary"] = employees["Salary"] * 12
employees["Annual_Salary"]
#first name :
employees["First_Name"] = employees["Name"].str.split(" ").str[0]
employees["First_Name"]
#performance level
employees["Performance_Level"] = np.where(
    employees["Performance"] >= 90,
    "Excellent",
    np.where(
        employees["Performance"] >= 80,
        "Good",
        np.where(
            employees["Performance"] >= 70,
            "Average",
            "Needs Improvement"
        )
    )
)

employees["Performance_Level"]

#merged 2 
merged2 =pd.merge(
    employees,
    departments,
    on = "Department",
    how = "inner"
)

keep_emp = merged2[merged2["Department"].isin(["IT","Sales"]) &
           (merged2["Performance"]>=80) &
           (merged2["Experience"]>=3)]

# Select the requested columns and sort by Performance in descending order
result = keep_emp[[
    "First_Name", 
    "Department", 
    "Manager", 
    "Annual_Salary", 
    "Experience", 
    "Performance", 
    "Performance_Level"
]].sort_values(by="Performance", ascending=False)

# Display the resulting DataFrame
print(result)

  First_Name Department     Manager  Annual_Salary  Experience  Performance  \
4      Karan         IT  Ms. Sharma         780000          10           95
1       Riya         IT  Ms. Sharma         660000           4           92
7      Sneha         IT  Ms. Sharma         696000           3           91
2      Rahul      Sales   Mr. Verma         576000           7           85
8      Rohit      Sales   Mr. Verma         624000           8           82

  Performance_Level
4         Excellent
1         Excellent
7         Excellent
2              Good
8              Good

In [69]:
# Q26 — Final Department Analytics
# Create a department-level report containing:
# - Department
# - Employees
# - Avg_Salary
# - Avg_Experience
# - Avg_Performance
# - Max_Salary
# Sort by Avg_Performance descending.

#Final Department Analytics
result2 = employees.groupby("Department").agg(
    Employees=("EmployeeID", "count"),
    Avg_Salary=("Salary", "mean"),
    Avg_Experience=("Experience", "mean"),
    Avg_Performance=("Performance", "mean"),
    Max_Salary=("Salary", "max")
).reset_index()

result3= result2.sort_values(
    by="Avg_Performance",
    ascending = False
)
result3

,Department,Employees,Avg_Salary,Avg_Experience,Avg_Performance,Max_Salary
1,IT,3,59333.333333,5.666667,92.666667,65000
0,HR,3,42666.666667,3.333333,79.333333,45000
2,Sales,4,43500.000000,4.500000,78.250000,52000